// <auto-generated />
using FSEdu.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FSEdu.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601000000_AddNotificationPreferences")]
    partial class AddNotificationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Hand-written migration. Snapshot will be regenerated by
            // `dotnet ef migrations add` once the API process is stopped.
        }
    }
}
