// <auto-generated />
using FSEdu.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FSEdu.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426061000_AddLessonQuestions")]
    partial class AddLessonQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // NOTE: Hand-written migration. The full snapshot lives in
            // ApplicationDbContextModelSnapshot.cs and will be regenerated
            // the next time `dotnet ef migrations add` runs cleanly (i.e.
            // after the API process is stopped). EF only needs the
            // [Migration] attribute above to discover this migration at
            // runtime; BuildTargetModel is consulted by tooling for diffs,
            // not by Migrator.ApplyMigrations.
        }
    }
}
